version: 2

workflows:
    version: 2

    pipeline:
        jobs:
            - build_and_test
            - validate_coverage:
                requires: [ build_and_test ]

jobs:
    build_and_test:
        docker: [ { image: 'circleci/php:7.2' } ]
        steps:
            - checkout

            - run: |
                cd project
                composer install
                phpdbg -qrr vendor/bin/phpunit

            - persist_to_workspace: { root: '.', paths: [ '.' ] }

    validate_coverage:
        docker: [ { image: 'skluck/circleci-required-coverage:latest' } ]
        environment:
            - BASE_BRANCH: "master"
            # - REQUIRED_TEST_COVERAGE_INCREASE # Set this environment variable in Circle environment variables to make this more dynamic. Default: 1%

        steps:
            - attach_workspace: { at: '.' }

            - run:
                name: "Save unit test coverage"
                command: |
                    echo "$(php generate-total-coverage.php ./project/clover.xml)" >> ./coverage
                    echo "${CIRCLE_SHA1}" >> ./current_commit_sha

                    echo "Current code coverage: $(cat ./coverage)"

            - save_cache:
                key: 'v1-unit-test-coverage-{{ checksum "current_commit_sha" }}'
                paths: [ './coverage' ]

            - run:
                name: "Get unit test coverage of main branch"
                command: |
                    if [ "${CIRCLE_BRANCH}" == "${BASE_BRANCH}" ] ; then
                        echo "Running on base branch. Skipping unit test coverage comparison."
                        touch ./head_commit_sha
                        exit 0
                    fi

                    main_branch_sha=$(
                        ./fetch-target-sha.sh \
                            --user ${CIRCLE_PROJECT_USERNAME} \
                            --repo ${CIRCLE_PROJECT_REPONAME} \
                            --branch "${BASE_BRANCH}"
                        )

                    echo ${main_branch_sha} >> ./head_commit_sha
                    mv ./coverage ./current_coverage

                    echo "Current SHA of main branch: $(cat ./head_commit_sha)"

            - restore_cache:
                keys: [ 'v1-unit-test-coverage-{{ checksum "head_commit_sha" }}' ]

            - run:
                name: "Comparing coverage of current branch against main branch"
                command: |
                    if [ "${CIRCLE_BRANCH}" == "${BASE_BRANCH}" ] ; then
                        echo "Running on base branch. Skipping unit test coverage comparison."
                        exit 0
                    fi

                    current_coverage=$(cat ./current_coverage)
                    required_increase="${REQUIRED_TEST_COVERAGE_INCREASE:-1}"

                    head_coverage=""
                    if [ -f ./coverage ] ; then
                        head_coverage=$(cat ./coverage)
                    fi

                    ./compare-coverage.sh ${current_coverage} ${head_coverage} ${required_increase}
