version: 2

workflows:
    version: 2

    pipeline:
        jobs:
            - build_and_test
            - validate_coverage:
                requires: [ build_and_test ]

jobs:
    build_and_test:
        docker: [ { image: 'circleci/php:7.2' } ]
        steps:
            - checkout

            - run: |
                cd project
                composer install
                phpdbg -qrr vendor/bin/phpunit

            - persist_to_workspace: { root: '.', paths: [ '.' ] }

    validate_coverage:
        docker: [ { image: 'skluck/circleci-required-coverage:1.0-alpine' } ]
        environment:
            - BASE_BRANCH: "master"
            # - REQUIRED_TEST_COVERAGE_INCREASE # Set this environment variable in Circle environment variables to make this more dynamic. Default: 1%

        steps:
            - attach_workspace: { at: '.' }

            - run:
                name: "Save unit test coverage"
                command: |
                    ./generate-total-coverage.sh \
                        --clover "$(pwd)/project/clover.xml" \
                        --output "$(pwd)/coverage" \
                        --commit "${CIRCLE_SHA1}" \
                        --commit-file "$(pwd)/current_commit_sha"

            - save_cache:
                key: 'v1-unit-test-coverage-{{ checksum "current_commit_sha" }}'
                paths: [ './coverage' ]

            - run:
                name: "Get unit test coverage of main branch"
                command: |
                    mv ./coverage ./current_coverage
                    ./fetch-target-sha.sh \
                        --user ${CIRCLE_PROJECT_USERNAME} \
                        --repo ${CIRCLE_PROJECT_REPONAME} \
                        --base-branch "${BASE_BRANCH}" \
                        --current-branch "${CIRCLE_BRANCH}" \
                        --commit-file "$(pwd)/base_commit_sha"

            - restore_cache:
                keys: [ 'v1-unit-test-coverage-{{ checksum "base_commit_sha" }}' ]

            - run:
                name: "Comparing coverage of current branch against main branch"
                command: |
                    ./ensure-code-coverage-is-increased.sh \
                        --base-branch "${BASE_BRANCH}" \
                        --current-branch "${CIRCLE_BRANCH}" \
                        --base-coverage "$(cat ./coverage 2>/dev/null || true)" \
                        --current-coverage "$(cat ./current_coverage)"
